// Source code is decompiled from a .class file using FernFlower decompiler.
public class DessertDetails {
   public DessertDetails() {
   }

   public static void main(String[] var0) {
      Dessert var1 = new Dessert();
      var1.dessertID = 1;
      var1.dessertName = "Chocolate Cake";
      var1.price = 350.0;
      var1.quantityAvailable = 20;
      var1.isVegan = false;
      var1.calories = 500;
      System.out.println("Dessert ID: " + var1.dessertID);
      System.out.println("Dessert Name: " + var1.dessertName);
      System.out.println("Price: " + var1.price);
      System.out.println("Quantity Available: " + var1.quantityAvailable);
      System.out.println("Is Vegan: " + var1.isVegan);
      System.out.println("Calories: " + var1.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
      Dessert var2 = new Dessert();
      var2.dessertID = 2;
      var2.dessertName = "Strawberry Cheesecake";
      var2.price = 400.0;
      var2.quantityAvailable = 15;
      var2.isVegan = false;
      var2.calories = 450;
      System.out.println("Dessert ID: " + var2.dessertID);
      System.out.println("Dessert Name: " + var2.dessertName);
      System.out.println("Price: " + var2.price);
      System.out.println("Quantity Available: " + var2.quantityAvailable);
      System.out.println("Is Vegan: " + var2.isVegan);
      System.out.println("Calories: " + var2.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
      Dessert var3 = new Dessert();
      var3.dessertID = 3;
      var3.dessertName = "Vegan Brownie";
      var3.price = 300.0;
      var3.quantityAvailable = 10;
      var3.isVegan = true;
      var3.calories = 350;
      System.out.println("Dessert ID: " + var3.dessertID);
      System.out.println("Dessert Name: " + var3.dessertName);
      System.out.println("Price: " + var3.price);
      System.out.println("Quantity Available: " + var3.quantityAvailable);
      System.out.println("Is Vegan: " + var3.isVegan);
      System.out.println("Calories: " + var3.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
      Dessert var4 = new Dessert();
      var4.dessertID = 4;
      var4.dessertName = "Mango Ice Cream";
      var4.price = 200.0;
      var4.quantityAvailable = 25;
      var4.isVegan = false;
      var4.calories = 250;
      System.out.println("Dessert ID: " + var4.dessertID);
      System.out.println("Dessert Name: " + var4.dessertName);
      System.out.println("Price: " + var4.price);
      System.out.println("Quantity Available: " + var4.quantityAvailable);
      System.out.println("Is Vegan: " + var4.isVegan);
      System.out.println("Calories: " + var4.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
      Dessert var5 = new Dessert();
      var5.dessertID = 5;
      var5.dessertName = "Apple Pie";
      var5.price = 450.0;
      var5.quantityAvailable = 30;
      var5.isVegan = false;
      var5.calories = 400;
      System.out.println("Dessert ID: " + var5.dessertID);
      System.out.println("Dessert Name: " + var5.dessertName);
      System.out.println("Price: " + var5.price);
      System.out.println("Quantity Available: " + var5.quantityAvailable);
      System.out.println("Is Vegan: " + var5.isVegan);
      System.out.println("Calories: " + var5.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
      Dessert var6 = new Dessert();
      var6.dessertID = 6;
      var6.dessertName = "Pineapple Pie";
      var6.price = 300.0;
      var6.quantityAvailable = 20;
      var6.isVegan = false;
      var6.calories = 450;
      System.out.println("Dessert ID: " + var6.dessertID);
      System.out.println("Dessert Name: " + var6.dessertName);
      System.out.println("Price: " + var6.price);
      System.out.println("Quantity Available: " + var6.quantityAvailable);
      System.out.println("Is Vegan: " + var6.isVegan);
      System.out.println("Calories: " + var6.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
      Dessert var7 = new Dessert();
      var7.dessertID = 7;
      var7.dessertName = "Lemon Tart";
      var7.price = 350.0;
      var7.quantityAvailable = 10;
      var7.isVegan = false;
      var7.calories = 300;
      System.out.println("Dessert ID: " + var7.dessertID);
      System.out.println("Dessert Name: " + var7.dessertName);
      System.out.println("Price: " + var7.price);
      System.out.println("Quantity Available: " + var7.quantityAvailable);
      System.out.println("Is Vegan: " + var7.isVegan);
      System.out.println("Calories: " + var7.calories);
      System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
   }
}
